# Generated by Django 6.1.1 on 2026-09-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restauranttable',
            name='capacity',
        ),
        migrations.AddField(
            model_name='restauranttable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='restauranttable',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
