# Generated by Django 6.1.1 on 2026-09-24 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0002_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.DecimalField(default=True),
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('description', models.CharField(default=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rms.food')),
            ],
        ),
    ]
