# Generated by Django 6.1.1 on 2026-09-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0002_remove_restauranttable_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restauranttable',
            name='qr_token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
