# Generated by Django 6.1.1 on 2026-09-26 09:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0003_restauranttable_qr_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restauranttable',
            name='qr_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
