# Generated by Django 6.1.1 on 2026-09-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0003_food_price_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='username',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
