# Generated by Django 6.1.1 on 2026-09-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0004_order_phone_order_username_alter_order_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
