# Generated by Django 6.1.1 on 2026-09-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0004_restauranttable_remove_order_table_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='special_instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
