# Generated by Django 6.1.1 on 2026-09-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0005_orderitem_status_alter_order_customer_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('served', 'Served')], default='pending', max_length=20),
        ),
    ]
