# Generated by Django 6.1.1 on 2026-09-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0006_cart'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(fields=('session_id', 'food'), name='unique_cart_food_per_session'),
        ),
    ]
