# Generated by Django 6.1.1 on 2026-09-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0008_alter_cart_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('served', 'Served')], default='pending', max_length=20),
        ),
    ]
